### ISSUE TITLE
Provide hints on derivation of wave equations on page 52?

### ISSUE THREAD

**Issue by alexdowad** [photonlines/Intuitive-Guide-to-Maxwells-Equations#8]
Page 52 just says to apply the vector identity curl(curl(F)) = grad(div(F)) - div(grad(F)) to equations 3 and 4 to derive the electromagnetic wave equations, but doesn't give any hint about how to do this. It baffled me for a while... but the great thing was that it stimulated me to search on the Internet and find a better explanation elsewhere.

Maybe a couple hints would be helpful? Perhaps in an appendix?

**Comment by alexdowad** [comment]
One of the bits which wasn't obvious to me at first is that the time derivative of curl(F) is the same as curl(time derivative of F). Had to go back to the definition of curl to see that it was true.

**Comment by photonlines** [comment]
Hi Alex - I added in 2 links to clarify the derivation, as well as the actual equation itself. One of the links is provided here in case you're still looking for help on this: http://maxwells-equations.com/equations/wave.php
